"""VLM 跟踪所需的视觉上下文构造。"""

from .builder import (
    PROMPT_PROFILE_VISUAL_V5,
    PROMPT_PROFILE_VLT_V6,
    PROMPT_PROFILES,
    SAFE_INIT_LANGUAGE_SCOPES,
    ContextBuildResult,
    TrackingContextBuilder,
    history_layout_for_prompt_profile,
    is_unsafe_init_language_scope,
    validate_prompt_profile,
)
from .visual import (
    DEFAULT_VISUAL_MARKER_STYLE,
    HISTORY_LAYOUT_COMPACT_GRID_V1,
    HISTORY_LAYOUT_RECENT_STRIP_3_V1,
    HISTORY_LAYOUT_RECENT_STRIP_3_V2,
    HISTORY_LAYOUTS,
    HISTORY_STRIP_SEPARATOR_COLOR_RGB,
    HISTORY_STRIP_SEPARATOR_RATIO,
    REFERENCE_MODE_BBOX_TEXT,
    REFERENCE_MODE_VISUAL_BOX,
    REFERENCE_MODES,
    VISUAL_MARKER_VERSION,
    VisualMarkerStyle,
    arrange_history_items,
    build_history_mosaic,
    draw_reference_box,
    validate_reference_mode,
)

__all__ = [
    "ContextBuildResult",
    "DEFAULT_VISUAL_MARKER_STYLE",
    "HISTORY_LAYOUT_COMPACT_GRID_V1",
    "HISTORY_LAYOUT_RECENT_STRIP_3_V1",
    "HISTORY_LAYOUT_RECENT_STRIP_3_V2",
    "HISTORY_LAYOUTS",
    "HISTORY_STRIP_SEPARATOR_COLOR_RGB",
    "HISTORY_STRIP_SEPARATOR_RATIO",
    "PROMPT_PROFILES",
    "PROMPT_PROFILE_VISUAL_V5",
    "PROMPT_PROFILE_VLT_V6",
    "SAFE_INIT_LANGUAGE_SCOPES",
    "is_unsafe_init_language_scope",
    "REFERENCE_MODE_BBOX_TEXT",
    "REFERENCE_MODE_VISUAL_BOX",
    "REFERENCE_MODES",
    "TrackingContextBuilder",
    "VISUAL_MARKER_VERSION",
    "VisualMarkerStyle",
    "arrange_history_items",
    "build_history_mosaic",
    "draw_reference_box",
    "history_layout_for_prompt_profile",
    "validate_reference_mode",
    "validate_prompt_profile",
]
