"""公开的 CognitiveTrack v4 协议接口。"""

from .bbox import (
    BBOX_PROTOCOL_NORM1000,
    BBOX_PROTOCOL_QWEN_ABS_PIXEL,
    BBOX_PROTOCOLS,
    MEMORY_UPDATE_JSON_KEY,
    TARGET_STATUS_JSON_KEY,
    BBoxXYWH,
    BBoxXYXY,
    bbox_iou_xywh,
    bbox_protocol_json_key,
    clip_xywh,
    model_pixel_xyxy_to_pixel_xywh,
    norm1000_xyxy_to_pixel_xywh,
    pixel_xywh_to_model_pixel_xyxy,
    pixel_xywh_to_norm1000_xyxy,
    validate_bbox_protocol,
    validate_norm1000_xyxy,
    validate_xywh,
    validate_xyxy,
    xywh_to_xyxy,
    xyxy_to_xywh,
)
from .enums import (
    ExecutionStatus,
    GroundTruthPresence,
    IdentityMatch,
    Localizability,
    TargetPresence,
)
from .exceptions import BoundingBoxError, ModelOutputParseError, ProtocolValidationError
from .schema import (
    SCHEMA_VERSION,
    CognitionInfo,
    ContextInfo,
    ExecutionInfo,
    FrameResult,
    GroundTruth,
    Prediction,
)

__all__ = [
    "BBOX_PROTOCOLS",
    "BBOX_PROTOCOL_NORM1000",
    "BBOX_PROTOCOL_QWEN_ABS_PIXEL",
    "BBoxXYWH",
    "BBoxXYXY",
    "BoundingBoxError",
    "CognitionInfo",
    "ContextInfo",
    "ExecutionInfo",
    "ExecutionStatus",
    "FrameResult",
    "GroundTruth",
    "GroundTruthPresence",
    "MEMORY_UPDATE_JSON_KEY",
    "TARGET_STATUS_JSON_KEY",
    "IdentityMatch",
    "Localizability",
    "ModelOutputParseError",
    "Prediction",
    "ProtocolValidationError",
    "SCHEMA_VERSION",
    "TargetPresence",
    "bbox_iou_xywh",
    "bbox_protocol_json_key",
    "clip_xywh",
    "model_pixel_xyxy_to_pixel_xywh",
    "norm1000_xyxy_to_pixel_xywh",
    "pixel_xywh_to_model_pixel_xyxy",
    "pixel_xywh_to_norm1000_xyxy",
    "validate_bbox_protocol",
    "validate_norm1000_xyxy",
    "validate_xywh",
    "validate_xyxy",
    "xywh_to_xyxy",
    "xyxy_to_xywh",
]
